In [1]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import sys
import torch.nn.functional as F

In [2]:
class Model(nn.Module):
    def __init__(self, input_features) -> None:
        super().__init__()
        self.linear = nn.Linear(input_features, 1)
        
    def forward(self, x):
        y = torch.sigmoid(self.linear(x))
        return y

In [3]:
model = Model(input_features=6)

# Lazy method

In [5]:
FILE = "model.pt"
torch.save(model, FILE)

In [6]:
model = torch.load(FILE)
model.eval()

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [8]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3138,  0.2928, -0.2299, -0.1612, -0.0234, -0.0619]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.1189], requires_grad=True)]

# Second model

In [10]:
torch.save(model.state_dict(), FILE)

In [11]:
Loaded_model = Model(input_features=6)
Loaded_model.load_state_dict(torch.load(FILE))
model.eval()
list(model.parameters())

[Parameter containing:
 tensor([[-0.3138,  0.2928, -0.2299, -0.1612, -0.0234, -0.0619]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.1189], requires_grad=True)]

In [12]:
model.state_dict()

OrderedDict([('linear.weight',
              tensor([[-0.3138,  0.2928, -0.2299, -0.1612, -0.0234, -0.0619]])),
             ('linear.bias', tensor([-0.1189]))])

# Saving checkpoint

In [22]:
lr = 0.001
optimizer = torch.optim.Adadelta(model.parameters(), lr=lr)

optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'rho': 0.9,
   'eps': 1e-06,
   'weight_decay': 0,
   'maximize': False,
   'foreach': None,
   'params': [0, 1]}]}

In [23]:
checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "optim_state": optimizer.state_dict(),
}

In [24]:
torch.save(checkpoint, "checkpoint.pt")

In [25]:
loaded_checkpoint = torch.load("checkpoint.pt")
loaded_checkpoint

{'epoch': 90,
 'model_state': OrderedDict([('linear.weight',
               tensor([[-0.1144,  0.2947, -0.2495,  0.0365, -0.0530, -0.1932]])),
              ('linear.bias', tensor([-0.0203]))]),
 'optim_state': {'state': {},
  'param_groups': [{'lr': 0.001,
    'rho': 0.9,
    'eps': 1e-06,
    'weight_decay': 0,
    'maximize': False,
    'foreach': None,
    'params': [0, 1]}]}}

In [26]:
model = Model(input_features=6)
optimizer = torch.optim.Adadelta(model.parameters(), lr=0)


In [27]:
epoch = loaded_checkpoint["epoch"]
model.load_state_dict(loaded_checkpoint["model_state"])
optimizer.load_state_dict(loaded_checkpoint["optim_state"])

In [28]:
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'rho': 0.9,
   'eps': 1e-06,
   'weight_decay': 0,
   'maximize': False,
   'foreach': None,
   'params': [0, 1]}]}

map_location, when model in cuda